#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  # REPO_BRANCH: 20230609
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  DOCKER_BUILD_SH: build.sh
  CACHE_TOOLCHAIN: true

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      DEVICE_TARGET: ${{ steps.variable.outputs.DEVICE_TARGET }}
      DEVICE_SUBTARGET: ${{ steps.variable.outputs.DEVICE_SUBTARGET }} 
    steps:
    - name: æ£€æŸ¥é¡¹ç›®åˆ†æ”¯
      uses: actions/checkout@v4

    - name: å®‰è£…ç¼–è¯‘çŽ¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -qq install libfuse-dev $(curl -fsSL git.io/depends-ubuntu-2204)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          sudo apt-get install -y clang

    - name: å…‹éš†å›ºä»¶æºç 
      id: clone
      run: |
        df -hT $GITHUB_WORKSPACE
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
         
    - name: Generate Variables
      id: variable
      run: |
        cp $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        make defconfig > /dev/null 2>&1
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_OUTPUT
        DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_OUTPUT   


    - name: æ·»åŠ å¤–éƒ¨æ’ä»¶
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: æ›´æ–°å¤–éƒ¨æ’ä»¶
      run: cd openwrt && ./scripts/feeds update -a

    - name: Toolchainç¼“å­˜
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        prefix: ${{ env.OPENWRT_PATH }}
        
    - name: å®‰è£…å¤–éƒ¨æ’ä»¶
      run: cd openwrt && ./scripts/feeds install -a

    - name: åŠ è½½ä¸ªäººè®¾ç½®
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}


    - name: ä¸‹è½½å›ºä»¶dLåº“
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    # - name: upload .config file
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: lean-config
    #     path: openwrt/.config
    
    # - name: Generate release tag
    #   id: tag-config
    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
    #   run: |
    #     echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
    #     touch release.txt
    #     echo "status=success" >> $GITHUB_OUTPUT
  
    # - name: Upload config to release
    #   uses: softprops/action-gh-release@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.tag-config.outputs.release_tag }}
    #     body_path: release.txt
    #     files: openwrt/.config

    - name: æ­£åœ¨ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: æŸ¥çœ‹ç£ç›˜ç”¨é‡
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: æ‰“åŒ…ä¸Šä¼ å›ºä»¶
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: åˆ›å»ºå‘å¸ƒæ ‡ç­¾
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        # echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "ðŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "ðŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: å‘å¸ƒæ–°ç‰ˆå›ºä»¶
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    # - name: æ¸…ç†ç¼–è¯‘æµç¨‹
    #   uses: Mattraks/delete-workflow-runs@main
    #   with:
    #     retain_days: 1
    #     keep_minimum_runs: 2

    # - name: åˆ é™¤æ—§ç‰ˆå›ºä»¶
    #   uses: dev-drprasad/delete-older-releases@master
    # #  uses: dev-drprasad/delete-older-releases@v0.1.0
    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
    #   with:
    #     keep_latest: 2
    #     delete_tags: true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: æž„é€ dockeré•œåƒ
      id: push
      run: |
        cd $GITHUB_WORKSPACE/dockerx86
        cp $GITHUB_WORKSPACE/openwrt/bin/targets/x86/64/openwrt-x86-64-generic-rootfs.tar.gz $GITHUB_WORKSPACE/dockerx86/
        mv openwrt-x86-64-generic-rootfs.tar.gz openwrt-x86-64-default-rootfs.tar.gz  
        chmod +x $DOCKER_BUILD_SH
        ./$DOCKER_BUILD_SH
        gzip -dc docker-img-openwrt-x86-latest.gz | docker load
        docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_TOKEN }}
        docker tag mhy123152/lean-rootfs mhy123152/lean-rootfs:${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }} mhy123152/lean-rootfs:${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.REPO_BRANCH }}
        docker push mhy123152/lean-rootfs
        echo "status=success" >> $GITHUB_OUTPUT


  # push-rootfs-container:
  #   name: RootFS
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: needs.generate_matrix.outputs.rootfs != '{"include":[]}'
  #   strategy:
  #     fail-fast: False
  #     matrix: ${{fromJson(needs.generate_matrix.outputs.rootfs)}}

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
  #         path: ./

  #     - name: Set up QEMU
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y qemu-user-static binfmt-support
  #         sudo update-binfmts --import

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to GitHub Container Registry
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Login to Docker.io Container Registry
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USER }}
  #         password: ${{ secrets.DOCKER_TOKEN }}

  #     - name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: |
  #           ghcr.io/mhy123152/lean-rootfs
  #           docker.io/mhy123152/lean-rootfs
  #         flavor: |
  #           latest=false
  #           prefix=${{ env.PREFIX }}
  #         tags: |
  #           ${{ matrix.target }}-${{ needs.generate_matrix.outputs.ref }}
  #           ${{ matrix.target }}-${{ needs.generate_matrix.outputs.version }}
  #           ${{ matrix.target }}-master,enable=${{ needs.generate_matrix.outputs.ref == 'main' }}
  #           ${{ matrix.target }},enable=${{ needs.generate_matrix.outputs.version == 'SNAPSHOT' }}
  #           ${{ matrix.arch }}-${{ needs.generate_matrix.outputs.ref }}
  #           ${{ matrix.arch }}-${{ needs.generate_matrix.outputs.version }}
  #           ${{ matrix.arch }}-master,enable=${{ needs.generate_matrix.outputs.ref == 'main' }}
  #           ${{ matrix.arch }},enable=${{ needs.generate_matrix.outputs.version == 'SNAPSHOT' }}
  #           latest,enable=${{ needs.generate_matrix.outputs.version == 'SNAPSHOT' && matrix.target == 'x86/64'}}

  #     - name: Generate build args
  #       id: build_args
  #       run: |
  #         echo 'args<<EOF
  #           ROOTFS_FILE=${{ needs.build.outputs.release_tag }}
  #           USER=root
  #           CMD="/bin/ash"
  #         EOF' >> $GITHUB_OUTPUT

  #     - name: Build
  #       id: build
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         push: false
  #         tags: ${{ steps.meta.outputs.tags }}
  #         load: true
  #         build-args: ${{ steps.build_args.outputs.args }}
  #         labels: ${{ steps.meta.outputs.labels }}
  #         platforms: linux/${{ matrix.arch }}

  #     - name: Smoke test
  #       run: docker run --platform=linux/${{ matrix.arch }} ${{ steps.build.outputs.imageid }} uname -m

  #     - name: Push
  #       if: github.event_name != 'pull_request'
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         build-args: ${{ steps.build_args.outputs.args }}
  #         labels: ${{ steps.meta.outputs.labels }}
  #         platforms: linux/${{ matrix.arch }}